// lib/mockData.js

export const MOCK_WORKERS = [
  {
    uid: "demo-worker-id",
    name: "Demo Worker",
    email: "worker@demo.com",
    role: "worker",
    skill: "electrician",
    hourlyRate: 800,
    isVerified: true,
    rating: 4.8,
    reviewCount: 25,
    location: "Lahore",
    isOnline: true,
    bio: "Professional electrician with 10 years of experience in house wiring and appliance repair.",
    experience: 10,
    jobsCompleted: 150,
  },
  {
    uid: "mock-1",
    name: "Ahmad Khan",
    skill: "plumber",
    hourlyRate: 500,
    isVerified: true,
    rating: 4.5,
    reviewCount: 12,
    location: "Lahore",
    isOnline: true,
    bio: "Expert plumber for all your leakages and pipe fixes.",
    experience: 5,
  },
  {
    uid: "mock-2",
    name: "Ali Sheikh",
    skill: "carpenter",
    hourlyRate: 700,
    isVerified: false,
    rating: 4.2,
    reviewCount: 8,
    location: "Karachi",
    isOnline: true,
    bio: "Custom furniture and wood repair specialist.",
    experience: 8,
  },
  {
    uid: "mock-3",
    name: "Hamza Ali",
    skill: "painter",
    hourlyRate: 400,
    isVerified: true,
    rating: 4.9,
    reviewCount: 45,
    location: "Islamabad",
    isOnline: true,
    bio: "Wall painting and decorative finishes expert.",
    experience: 12,
  },
  {
    uid: "mock-4",
    name: "Usman Malik",
    skill: "electrician",
    hourlyRate: 600,
    isVerified: true,
    rating: 4.7,
    reviewCount: 20,
    location: "Faisalabad",
    isOnline: false,
    bio: "Reliable electrician for domestic and commercial work.",
    experience: 6,
  },
  // Adding more to reach 30+
  ...Array.from({ length: 30 }).map((_, i) => ({
    uid: `mock-seed-${i}`,
    name: ["Bilal", "Zaid", "Hassan", "Mustafa", "Ibrahim", "Sajid", "Rashid", "Kamran", "Faisal", "Arsalan"][i % 10] + " " + (i % 2 === 0 ? "Khan" : "Ahmed"),
    skill: ["plumber", "electrician", "carpenter", "painter", "driver", "gardener", "cleaner", "cook", "barber", "tech_repair", "mechanic"][i % 11],
    hourlyRate: 300 + (i * 20),
    isVerified: i % 3 === 0,
    rating: 3.5 + (i % 15) / 10,
    reviewCount: i * 2,
    location: ["Lahore", "Karachi", "Islamabad", "Multan", "Peshawar", "Quetta"][i % 6],
    isOnline: i % 2 === 0,
    bio: "Professional services with guaranteed satisfaction.",
    experience: 2 + (i % 8),
  }))
];

export const DEMO_CUSTOMER = {
  uid: "demo-customer-id",
  name: "Demo Customer",
  email: "customer@demo.com",
  role: "customer",
  phone: "03001234567",
};
